"use strict";

// Full vault-AA lifecycle test (security-hardened AA):
//   deposit -> submit -> candidate replacement -> early lock bounce ->
//   timetravel +600s -> lock -> early withdraw bounce ('not finalized') ->
//   challenge + respond success path (unfreeze, recorded bond fully
//   confiscated -> bond_ var zeroed) ->
//   challenge failure path (no respond, window over -> height failed,
//   last_locked rollback, bond stays credited) -> alice reclaims her bond
//   via {claim_bond} -> resubmit/lock/finalize -> proof-gated withdraw
//   (good proof pays; bad proof bounces; identical replay bounces via the
//   cumulative wd_<h>_<addr> cap).
//
// The withdrawal proof is generated by:
//   cargo run -p operp-settle --example gen_withdraw_proof
// which writes obyte-local/withdraw_claim.json.
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const aaRoot = path.join(__dirname, "..", "vendor", "aa-testkit");
const nm = path.join(aaRoot, "node_modules");
process.env.NODE_PATH = [nm, process.env.NODE_PATH].filter(Boolean).join(path.delimiter);
process.env.devnet = "1";
if (process.env.AA_DEBUG_COMPLEXITY) process.env.MAX_COMPLEXITY = "99999";
require("module").Module._initPaths();

// The vault AA references the PERP governance asset via the literal
// placeholder 'PERP_ASSET_ID_HERE'. Production deploy scripts substitute
// the real asset id. For THIS initial devnet deployment no PERP asset
// exists yet, so we substitute 'base' (always valid at definition-check
// time); base can never reach the perp-deposit branch because that branch
// is keyed on trigger.data.deposit_perp, not deposit. The real PERP-backed
// instance is redeployed inside the PERP section below with the issued
// asset id.
const BOOTSTRAP_AA = path.join(__dirname, "agents", "operp_vault_base.aa");
fs.writeFileSync(
  BOOTSTRAP_AA,
  fs
    .readFileSync(path.join(__dirname, "agents", "operp_vault.aa"), "utf8")
    .replace(/PERP_ASSET_ID_HERE/g, "base")
);

const { generateMnemonic, getFirstAddress } = require(path.join(aaRoot, "src", "utils"));
const ALICE_MNEMONIC = generateMnemonic();
const BOB_MNEMONIC = generateMnemonic();
const { Testkit } = require(path.join(aaRoot, "main.js"));
const { Network } = Testkit({
  TESTDATA_DIR: path.join(__dirname, "testdata"),
  NETWORK_PORT: 16612,
});

function sha256Hex(s) {
  return crypto.createHash("sha256").update(s, "utf8").digest("hex");
}

async function trigger(wallet, data, amount) {
  const { unit, error } = await wallet.triggerAaWithData({
    toAddress: network.agent.vault,
    amount: amount === undefined ? 10000 : amount,
    data,
  });
  if (error) throw new Error(JSON.stringify(data).slice(0, 60) + ": " + error);
  await network.witnessUntilStable(unit);
  return unit;
}

async function vars() {
  const v = await network.wallet.alice.readAAStateVars(network.agent.vault);
  return v.vars || v;
}

async function expectBounce(promiseFn, needle) {
  const res = await promiseFn();
  const bounced =
    (res && res.bounced) ||
    (res && res.response && res.response.bounced) ||
    (res && res.objResponse && res.objResponse.bounced);
  const log = JSON.stringify(res || {});
  if (!bounced) throw new Error("expected bounce containing '" + needle + "', got: " + log.slice(0, 400));
  if (needle && !log.includes(needle))
    throw new Error("bounce reason mismatch: wanted '" + needle + "' in " + log.slice(0, 400));
  console.log("  bounced as expected:", needle);
}

// witnessUntilStable does not surface AA bounces; fetch the AA response instead.
async function triggerRaw(wallet, data, amount) {
  const { unit } = await wallet.triggerAaWithData({
    toAddress: network.agent.vault,
    amount: amount === undefined ? 10000 : amount,
    data,
  });
  await network.witnessUntilStable(unit);
  // network.getAaResponseToUnit resolves { response: { bounced, info, ... } }
  const res = await network.getAaResponseToUnit(unit);
  return { unit, response: (res && res.response) || null };
}


// ==================== PERP governance E2E helpers (plan steps 7-8) ====================
//
// Sidechain ops below are signed and encoded byte-for-byte like the Rust DAG
// (crates/operp-dag::canonical_bytes, gov tags 8..13) and serialized exactly
// like serde_json::to_value(&op): externally tagged variant names with
// snake_case fields; AccountId/[u8;N] as arrays of numbers, ints as numbers.
// Nothing on-chain re-verifies these signatures (the AA only commits roots),
// but faithful encoding means a watcher replaying this batch through
// operp-settle accepts it.

// Fallback PERP id (plan Assumptions): a fixed arbitrary id posted manually as
// simulated PERP when the testkit cannot issue a real asset.
const SIMULATED_PERP_ASSET = Buffer.alloc(32, 9).toString("base64");
// Resolved at runtime by resolvePerpAsset(); null -> skip only the PERP section.
let PERP_ASSET = null;

async function resolvePerpAsset(wallet) {
  // 1) real divisible-asset issuance through the vendored testkit
  //    (asset id = the definition unit id, same as NetworkInitializer does)
  try {
    const address = await wallet.getAddress();
    const created = await wallet.createAsset({
      is_private: false,
      is_transferrable: true,
      auto_destroy: false,
      fixed_denominations: false,
      issued_by_definer_only: true,
      cosigned_by_definer: false,
      spender_attested: false,
    });
    if (!created.error && created.unit) {
      await network.witnessUntilStable(created.unit);
      const issued = await wallet.issueDivisibleAsset({
        asset: created.unit,
        paying_addresses: [address],
        fee_paying_addresses: [address],
        change_address: address,
        to_address: address,
        amount: 1e12,
      });
      if (!issued.error && issued.unit) {
        await network.witnessUntilStable(issued.unit);
        console.log("issued PERP asset:", created.unit);
        return created.unit;
      }
      console.log("issueDivisibleAsset failed:", issued.error);
    } else {
      console.log("createAsset failed:", created.error);
    }
  } catch (e) {
    console.log("PERP asset issuance unavailable:", e && e.message ? e.message : e);
  }
  // 2) fallback: any consistent arbitrary id sent via a manual payment
  try {
    const r = await wallet.sendMulti({
      asset: SIMULATED_PERP_ASSET,
      to_address: await wallet.getAddress(),
      amount: 1e12,
    });
    if (!r.error && r.unit) {
      await network.witnessUntilStable(r.unit);
      console.log("using SIMULATED PERP asset:", SIMULATED_PERP_ASSET);
      return SIMULATED_PERP_ASSET;
    }
    console.log("simulated PERP fallback failed:", r.error);
  } catch (e) {
    console.log("simulated PERP fallback unavailable:", e && e.message ? e.message : e);
  }
  return null;
}

function sha256Buf(buf) {
  return crypto.createHash("sha256").update(buf).digest();
}

function ed25519FromSeed(seed) {
  // wrap the raw 32-byte seed in PKCS#8 DER -> node crypto KeyObject
  const der = Buffer.concat([
    Buffer.from("302e020100300506032b657004220420", "hex"),
    seed,
  ]);
  const priv = crypto.createPrivateKey({ key: der, format: "der", type: "pkcs8" });
  const spki = crypto.createPublicKey(priv).export({ format: "der", type: "spki" });
  return { priv, pubkey: spki.subarray(spki.length - 32) };
}

function u32le(n) {
  const b = Buffer.alloc(4);
  b.writeUInt32LE(n);
  return b;
}
function u64le(n) {
  const b = Buffer.alloc(8);
  b.writeBigUInt64LE(BigInt(n));
  return b;
}
function u128le(n) {
  // Node lacks writeBigUInt128LE — emit as two little-endian u64 halves.
  const b = Buffer.alloc(16);
  const v = BigInt(n);
  b.writeBigUInt64LE(v & 0xffffffffffffffffn, 0);
  b.writeBigUInt64LE(v >> 64n, 8);
  return b;
}

// Mirror of operp_dag::canonical_bytes for the gov tags only (trailing pubkey
// appended, exactly like the full match there).
function govCanonicalBytes(parentsHex, opName, f, pubkey) {
  const parts = [Buffer.from("ODX1", "utf8"), Buffer.from([parentsHex.length])];
  for (const p of parentsHex) parts.push(Buffer.from(p, "hex"));
  const tag = {
    GovDeposit: 8,
    GovWithdraw: 9,
    CreateMarket: 10,
    CreateProposal: 11,
    Vote: 12,
    FinalizeProposal: 13,
  }[opName];
  if (tag === undefined) throw new Error("unsupported op " + opName);
  parts.push(Buffer.from([tag]));
  switch (opName) {
    case "GovDeposit": // account, amount u128, aa_unit
      parts.push(f.account, u128le(f.amount), f.aa_unit);
      break;
    case "GovWithdraw": // account, amount u128, nonce u64
      parts.push(f.account, u128le(f.amount), u64le(f.nonce));
      break;
    case "CreateMarket": // creator, symbol[16], tick, im/mm/taker/keeper bps (u64 each)
      parts.push(
        f.creator,
        f.symbol,
        u64le(f.tick_size),
        u64le(f.im_bps),
        u64le(f.mm_bps),
        u64le(f.taker_fee_bps),
        u64le(f.keeper_reward_bps),
      );
      break;
    case "CreateProposal": // creator, market u32, key u8, value u64
      parts.push(f.creator, u32le(f.market), Buffer.from([f.key]), u64le(f.value));
      break;
    case "Vote": // voter, proposal_id u64, approve u8
      parts.push(f.voter, u64le(f.proposal_id), Buffer.from([f.approve ? 1 : 0]));
      break;
    case "FinalizeProposal": // caller, proposal_id u64
      parts.push(f.caller, u64le(f.proposal_id));
      break;
  }
  parts.push(pubkey);
  return Buffer.concat(parts);
}

// Sign one gov op; returns the unit shaped exactly like
// operp_settle::Batch::temp_data_payload emits (serde-faithful op JSON).
function signGovUnit(parentsHex, opName, fieldsBuf, fieldsJson, key) {
  const id = sha256Buf(govCanonicalBytes(parentsHex, opName, fieldsBuf, key.pubkey));
  return {
    parents: parentsHex,
    op: { [opName]: fieldsJson },
    pubkey: key.pubkey.toString("hex"),
    sig: crypto.sign(null, id, key.priv).toString("hex"),
    unit_id: id.toString("hex"),
  };
}

// Hex-domain AA tree mirror of operp_state with the extended
// "acct:{addr}:{collateral}:{perp}" leaf (aa_leaf/aa_parent/aa_proof_for).
function aaLeafStr(addr, collateral, perp) {
  return sha256Hex("acct:" + addr + ":" + collateral + ":" + perp);
}
function aaProofFor(pairs, addr) {
  // pairs: [{ addr, collateral, perp }] with decimal-string balances
  const i = pairs.findIndex((p) => p.addr === addr);
  if (i < 0) throw new Error("no aa leaf for " + addr);
  const leaf = aaLeafStr(pairs[i].addr, pairs[i].collateral, pairs[i].perp);
  let level = pairs.map((p) => aaLeafStr(p.addr, p.collateral, p.perp)).sort();
  let idx = level.indexOf(leaf);
  const proof = [];
  while (level.length > 1) {
    if (level.length % 2 === 1) level.push(level[level.length - 1]);
    const sib = idx ^ 1;
    proof.push({ hash: level[sib], right: sib > idx });
    const next = [];
    for (let j = 0; j < level.length; j += 2) next.push(sha256Hex(level[j] + level[j + 1]));
    level = next;
    idx >>= 1;
  }
  return { proof, root: level[0] };
}

// Deterministic replay of exactly the ops posted in section 10, enforcing the
// same preconditions as operp-exec (fee burn, stake threshold, dedup,
// deadline, quorum), so every marker reflects applied state rather than
// wishful printing. Balances/supply are BigInt.
function makePerpEngine() {
  const CREATE_MARKET_FEE = 10000n;
  const PROPOSAL_MIN_STAKE = 1000n;
  const DURATION_SEQS = 20000;
  const QUORUM_NUM = 10n;
  const QUORUM_DEN = 100n;
  return {
    seq: 0,
    supply: 0n,
    bal: new Map(), // acct hex -> BigInt
    seenAaUnits: new Set(),
    markets: new Map(), // id -> params
    nextMarketId: 2, // BTC_USD=1 is genesis
    proposals: new Map(), // id -> proposal
    nextProposalId: 1,
    apply(opName, f) {
      const s = ++this.seq;
      switch (opName) {
        case "GovDeposit":
          if (this.seenAaUnits.has(f.aa_unit_hex)) throw new Error("replayed aa_unit");
          this.seenAaUnits.add(f.aa_unit_hex);
          this.bal.set(f.account_hex, (this.bal.get(f.account_hex) || 0n) + BigInt(f.amount));
          this.supply += BigInt(f.amount);
          return {};
        case "GovWithdraw": {
          const b = this.bal.get(f.account_hex) || 0n;
          const amt = BigInt(f.amount);
          if (b < amt) throw new Error("Insufficient PERP for GovWithdraw");
          this.bal.set(f.account_hex, b - amt);
          this.supply -= amt;
          return {};
        }
        case "CreateMarket": {
          const b = this.bal.get(f.creator_hex) || 0n;
          if (b < CREATE_MARKET_FEE) throw new Error("Insufficient listing fee");
          if (!f.tick_size || !f.im_bps || !f.mm_bps || !f.taker_fee_bps || !f.keeper_reward_bps)
            throw new Error("Risk: zero market parameter");
          this.bal.set(f.creator_hex, b - CREATE_MARKET_FEE);
          this.supply -= CREATE_MARKET_FEE;
          const id = this.nextMarketId++;
          this.markets.set(id, {
            symbol: Buffer.from(f.symbol_bytes).toString("utf8").replace(/\0+$/, ""),
            tick_size: f.tick_size,
            im_bps: f.im_bps,
            mm_bps: f.mm_bps,
            taker_fee_bps: f.taker_fee_bps,
            keeper_reward_bps: f.keeper_reward_bps,
            delisted: false,
          });
          return { market_id: id };
        }
        case "CreateProposal": {
          if (!this.markets.has(f.market)) throw new Error("NoMarket");
          if (f.key === 4 ? f.value !== 0 : f.value > 10000)
            throw new Error("Risk: bad proposal value");
          if ((this.bal.get(f.creator_hex) || 0n) < PROPOSAL_MIN_STAKE)
            throw new Error("Insufficient proposal stake");
          const pid = this.nextProposalId++;
          this.proposals.set(pid, {
            market: f.market,
            key: f.key,
            value: f.value,
            created_seq: s,
            deadline_seq: s + DURATION_SEQS,
            supply_at_create: this.supply,
            yes: 0n,
            no: 0n,
            voted: new Set(),
            finalized: null,
          });
          return { proposal_id: pid };
        }
        case "Vote": {
          const p = this.proposals.get(f.proposal_id);
          if (!p || p.finalized !== null || s >= p.deadline_seq)
            throw new Error("vote closed or unknown proposal");
          if (p.voted.has(f.voter_hex)) throw new Error("duplicate vote");
          p.voted.add(f.voter_hex);
          const w = this.bal.get(f.voter_hex) || 0n;
          if (f.approve) p.yes += w;
          else p.no += w;
          return {};
        }
        case "FinalizeProposal": {
          const p = this.proposals.get(f.proposal_id);
          if (!p || p.finalized !== null) throw new Error("NoProposal");
          if (s < p.deadline_seq) throw new Error("deadline not reached");
          const approved =
            p.yes > p.no && p.yes * QUORUM_DEN >= p.supply_at_create * QUORUM_NUM;
          p.finalized = approved;
          if (approved) {
            const m = this.markets.get(p.market);
            if (p.key === 4) m.delisted = true;
            else if (p.key === 0) m.im_bps = p.value;
            else if (p.key === 1) m.mm_bps = p.value;
            else if (p.key === 2) m.taker_fee_bps = p.value;
            else if (p.key === 3) m.keeper_reward_bps = p.value;
          }
          return { approved };
        }
        default:
          throw new Error("engine: unsupported op " + opName);
      }
    },
  };
}

// Batch data-availability reveal, identical to post_batch.js step 1
// (OIP-0007 temp_data with length/hash/data triple).
function getLength(value) {
  const cache = new WeakMap();
  function _len(v) {
    if (v === null) return 0;
    switch (typeof v) {
      case "string": return v.length;
      case "number": if (!isFinite(v)) throw new Error("bad number"); return 8;
      case "boolean": return 1;
      case "object": {
        if (cache.has(v)) return cache.get(v);
        let n = 0;
        if (Array.isArray(v)) { for (const el of v) n += _len(el); }
        else { for (const k of Object.keys(v)) n += k.length + _len(v[k]); }
        cache.set(v, n);
        return n;
      }
      default: throw new Error("unsupported type " + typeof v);
    }
  }
  return _len(value);
}

function obyteBase64Hash(obj) {
  const minified = JSON.stringify(obj, (k, v) => v, 0);
  return crypto.createHash("sha256").update(minified, "utf8").digest("base64");
}

function tempDataMessage(data) {
  return {
    app: "temp_data",
    payload_location: "inline",
    payload: {
      data_length: getLength(data),
      data_hash: obyteBase64Hash(data),
      data,
    },
  };
}

let network;

async function main() {
  network = await Network.create()
    .with.agent({ vault: BOOTSTRAP_AA })
    .with.wallet({ alice: 1e9, mnemonic: ALICE_MNEMONIC })
    .with.wallet({ bob: 1e9, mnemonic: BOB_MNEMONIC })
    .run();

  let alice, bob, aliceAddr, pv;
  const vault = network.agent.vault;
  alice = network.wallet.alice;
  bob = network.wallet.bob;
  console.log("vault", vault);

  // ---------- 1. deposit ----------
  await trigger(alice, { deposit: 1 }, 1e6);
  await trigger(bob, { deposit: 1 }, 2e6);
  let st = await vars();
  aliceAddr = await alice.getAddress();
  console.log("after deposits: bal_alice =", st["bal_" + aliceAddr]);
  if (!(st["bal_" + aliceAddr] > 0)) throw new Error("deposit not credited");

  // ---------- 1b. generate the REAL withdrawal claim (root committed at submit) ----------
  require("child_process").execSync(
    "cargo run -p operp-settle --example gen_withdraw_proof -- " + aliceAddr + " 1000000",
  );
  const claim = JSON.parse(fs.readFileSync(path.join(__dirname, "withdraw_claim.json"), "utf8"));
  console.log("claim:", claim.leaf_account, claim.collateral, "aa_root:", claim.aa_root);

  // sanity: recompute the root locally exactly like the AA does
  let lh = sha256Hex("acct:" + claim.leaf_account + ":" + claim.collateral + ":" + (claim.perp || "0"));
  for (const s of claim.proof) lh = sha256Hex(s.right ? lh + s.hash : s.hash + lh);
  if (lh !== claim.aa_root) throw new Error("local proof check mismatch: " + lh);
  console.log("local proof recheck OK");

  // ---------- 2. submit height 1 + candidate replacement ----------
  const submit1 = { submit: 1, chain_id: "operp-mvp-1", height: 1, prev_state_hash: "prev0", state_root: "rootCAND1", aa_root: "aacand1", fills_hash: "f1" };
  await trigger(bob, submit1);
  // second submit must REPLACE the first (pre-lock) — commits the REAL root
  const submit2 = { submit: 1, chain_id: "operp-mvp-1", height: 1, prev_state_hash: "prev0", state_root: "rootFINAL1", aa_root: claim.aa_root, fills_hash: "f1" };
  await trigger(alice, submit2);
  st = await vars();
  console.log("cand after replacement:", st["cand_root_1"], st["cand_aa_root_1"]);
  if (st["cand_root_1"] !== "rootFINAL1" || st["cand_aa_root_1"] !== claim.aa_root)
    throw new Error("candidate replacement failed");

  // ---------- 3. early lock must bounce ----------
  const earlyLock = await triggerRaw(bob, { lock: 1, height: 1 });
  if (!JSON.stringify(earlyLock).includes("cannot lock yet"))
    throw new Error("early lock did not bounce: " + JSON.stringify(earlyLock).slice(0, 300));
  console.log("  early lock bounced as expected");

  // ---------- 4. stability window then lock ----------
  await network.timetravel({ shift: '700s' });
  const lockRes = await triggerRaw(bob, { lock: 1, height: 1 });
  const lr = JSON.stringify(lockRes.response);
  console.log("lock response tail:", lr.slice(-300));
  st = await vars();
  console.log("after lock: root_1 =", st["root_1"], "last_locked =", st["last_locked"]);
  if (st["root_1"] !== "rootFINAL1" || Number(st["last_locked"]) !== 1) throw new Error("lock failed");

  // ---------- 5. withdraw before finalize bounces ----------
  const earlyWd = await triggerRaw(alice, { withdraw: 1, amount: 1000 });
  if (!JSON.stringify(earlyWd).includes("not finalizable"))
    throw new Error("early withdraw did not bounce: " + JSON.stringify(earlyWd).slice(0, 1500));
  console.log("  pre-finalize withdraw bounced as expected");

  // ---------- 6. challenge + respond SUCCESS ----------
  const chalUnit = await bob.triggerAaWithData({ toAddress: vault, amount: 30000, data: { challenge: 1, height: 1 } });
  if (chalUnit.error) throw new Error("challenge: " + chalUnit.error);
  await network.witnessUntilStable(chalUnit.unit);
  st = await vars();
  if (Number(st["frozen_1"]) !== 1) throw new Error("challenge did not freeze");
  console.log("  frozen_1 =", st.frozen_1, "bond_bob =", st["bond_" + (await bob.getAddress())]);

  await network.timetravel({ shift: '100s' });
  // identity gate: a non-operator (bob here — alice owns the final candidate)
  // must be rejected even with the correct root.
  const impostor = await triggerRaw(bob, { respond: 1, height: 1, root_confirmed: "rootFINAL1" }, 20000);
  if (!JSON.stringify(impostor).includes("not operator"))
    throw new Error("impostor respond not rejected: " + JSON.stringify(impostor).slice(0, 300));
  console.log("  impostor respond bounced as expected");
  await trigger(alice, { respond: 1, height: 1, root_confirmed: "rootFINAL1" }, 20000);
  st = await vars();
  if (Number(st["frozen_1"]) !== 0) throw new Error("respond did not unfreeze");
  const bobBondAfterConfiscation = st["bond_" + (await bob.getAddress())];
  console.log("  unfrozen; bob bond after confiscation =", bobBondAfterConfiscation);
  if (Number(bobBondAfterConfiscation) !== 0) throw new Error("respond did not confiscate the full recorded bond");
  const earlyFin = await triggerRaw(alice, { finalize: 1, height: 1 });
  if (!JSON.stringify(earlyFin).includes("cannot finalize"))
    throw new Error("early finalize did not bounce: " + JSON.stringify(earlyFin).slice(0, 200));
  console.log("  early finalize bounced as expected");

  // ---------- 8. challenge FAILURE path at height 2 ----------
  // submit+lock height 2 (bogus root), challenge it, never respond.
  await trigger(bob, { submit: 1, chain_id: "operp-mvp-1", height: 2, prev_state_hash: "rootFINAL1", state_root: "rootEVIL2", aa_root: "aaevil2", fills_hash: "f2" });
  await network.timetravel({ shift: '600s' });
  await trigger(bob, { lock: 1, height: 2 });
  st = await vars();
  if (st.root_2 !== "rootEVIL2") throw new Error("height2 lock failed");
  await alice.triggerAaWithData({ toAddress: vault, amount: 30000, data: { challenge: 1, height: 2 } })
    .then(async (r) => { if (r.error) throw new Error(r.error); await network.witnessUntilStable(r.unit); });
  await network.timetravel({ shift: '3600s' }); // operator stays silent past the window
  const failFin = await triggerRaw(alice, { finalize: 1, height: 2 }, 20000);
  st = await vars();
  console.log("after failed challenge: frozen_2 =", st.frozen_2, "last_locked =", st.last_locked);
  if (Number(st.frozen_2) !== 2) throw new Error("failure sweep did not mark frozen=2");
  if (Number(st.last_locked) !== 1) throw new Error("last_locked did not roll back");
  const aliceBondCredited = Number(st["bond_" + (await alice.getAddress())]);
  console.log("  alice bond stays credited =", aliceBondCredited);
  if (!(aliceBondCredited > 0)) throw new Error("challenger bond not credited after failed height");

  // ---------- 8b. challenger reclaims her recorded bond via {claim_bond} ----------
  // (fee headroom only: claiming must not cost more than the bond itself)
  // Payout proof is AA-atomic: the state message (bond_ = 0) applies only if
  // the payment message succeeded, so "did not bounce AND bond zeroed" proves
  // the bond was paid. Wallet-balance deltas are unreliable on devnet because
  // earlier payments settle asynchronously between the two getBalance calls.
  const bondClaim = await triggerRaw(alice, { claim_bond: 1 }, 30000);
  if (!bondClaim.response || bondClaim.response.bounced !== false)
    throw new Error("claim_bond bounced: " + JSON.stringify(bondClaim).slice(0, 400));
  st = await vars();
  if (Number(st["bond_" + aliceAddr]) !== 0) throw new Error("bond var not zeroed after claim_bond");
  console.log("  claim_bond paid out", aliceBondCredited, "bytes and zeroed the ledger");
  // ---------- 9. real proof withdraw against height 1 ----------
  // Height 1 was finalized? Not yet — we traveled far ahead; finalize h1 now.
  await trigger(alice, { finalize: 1, height: 1 });
  st = await vars();
  if (Number(st.last_finalized) !== 1) throw new Error("finalize h1 failed: last_finalized=" + st.last_finalized + " root_1=" + st.root_1 + " frozen_1=" + st.frozen_1 + " last_locked=" + st.last_locked);
  console.log("height 1 finalized");

  // claim was generated and its aa_root committed at submit time (section 1b)

  // fund the AA enough to pay (it holds deposits from step 1)
  const wdAmount = Math.min(Number(claim.collateral), 900000);
  const good = await triggerRaw(alice, {
    withdraw: 1,
    height: 1,
    amount: wdAmount,
    leaf_account: claim.leaf_account,
    collateral: claim.collateral,
    perp: claim.perp || "0",
    proof: claim.proof,
  });
  if (!(good.response && good.response.bounced === false && good.response.response_unit)) {
    throw new Error("good proof withdraw did not pay: " + JSON.stringify(good).slice(0, 500));
  }
  console.log("GOOD PROOF WITHDRAWAL PAID");

  // REPLAY: the identical withdraw a second time must bounce — the
  // cumulative wd_<h>_<addr> marker now equals the proven collateral,
  // tripping the cumulative-cap arm of the bad-claim-amount gate.
  const replay = await triggerRaw(alice, {
    withdraw: 1,
    height: 1,
    amount: wdAmount,
    leaf_account: claim.leaf_account,
    collateral: claim.collateral,
    perp: claim.perp || "0",
    proof: claim.proof,
  });
  if (!JSON.stringify(replay).includes("bad claim amount"))
    throw new Error("replay withdraw did not bounce: " + JSON.stringify(replay).slice(0, 400));
  console.log("REPLAY WITHDRAWAL BOUNCED AS EXPECTED");

  // bad proof must bounce. Use a small amount so the request passes the
  // cumulative wd_ cap (already filled by the good withdrawal) and actually
  // reaches the merkle-root verification arm.
  const badProof = claim.proof.map((s, i) => (i === 0 ? { ...s, hash: s.hash.slice(0, -1) + (s.hash.endsWith("0") ? "1" : "0") } : s));
  const bad = await triggerRaw(alice, {
    withdraw: 1,
    height: 1,
    amount: 1000,
    leaf_account: claim.leaf_account,
    collateral: claim.collateral,
    perp: claim.perp || "0",
    proof: badProof,
  });
  if (!JSON.stringify(bad).includes("bad merkle root"))
    throw new Error("bad proof did not bounce with 'bad merkle root': " + JSON.stringify(bad).slice(0, 2000));
  console.log("BAD PROOF BOUNCED AS EXPECTED");

  // Issue the PERP asset on THIS network while it is still running.
  PERP_ASSET = await resolvePerpAsset(alice);

  console.log("\nOK: full AA lifecycle passed");

  // ==================== 10. PERP governance E2E (plan steps 7-8) ====================
  // The leaf-format change is breaking, so — exactly like at issuance time —
  // the vault AA is REDEPLOYED here with 'PERP_ASSET_ID_HERE' replaced by the
  // runtime-resolved asset id (plan step 8). The fresh instance starts at
  // height 0, giving the gov batch a clean submit/lock/finalize run.
  if (!PERP_ASSET) {
    console.log("PERP E2E SKIPPED (no asset issuance)");
  } else {
    const aaSrc = fs
      .readFileSync(path.join(__dirname, "agents", "operp_vault.aa"), "utf8")
      .replace(/PERP_ASSET_ID_HERE/g, PERP_ASSET);
    const deployed = await alice.deployAgent(aaSrc);
    if (deployed.error || !deployed.address)
      throw new Error("PERP vault redeploy failed: " + deployed.error);
    await network.witnessUntilStable(deployed.unit);
    pv = deployed.address;
    console.log("PERP vault (redeployed with real asset id):", pv);

    // pv-targeted mirrors of the helpers above (those are bound to the
    // original vault instance).
    // NOTE: deliberately NOT using wallet.triggerAaWithData here — the
    // testkit child emits TWO 'aa_triggered' events for bounced triggers
    // (missing return in the error path), which permanently desynchronizes
    // the once()-based event pairing and hangs later triggers. Direct
    // sendMulti + explicit AA-response polling is race-free.
    const pTrigger = async (wallet, data, amount) => {
      const r = await wallet.sendMulti({
        base_outputs: [{ address: pv, amount: amount === undefined ? 10000 : amount }],
        messages: [{ app: "data", payload: data }],
      });
      if (r.error) throw new Error(JSON.stringify(data).slice(0, 60) + ": " + r.error);
      if (!r.unit) throw new Error(JSON.stringify(data).slice(0, 60) + ": no unit");
      await network.witnessUntilStable(r.unit);
      return r.unit;
    };
    const pTriggerRaw = async (wallet, data, amount) => {
      const unit = await pTrigger(wallet, data, amount);
      const res = await network.getAaResponseToUnit(unit);
      return { unit, response: (res && res.response) || null };
    };
    const pVars = async () => {
      const v = await alice.readAAStateVars(pv);
      return v.vars || v;
    };

    // ---- 10a. seed the fresh vault, then send PERP in and observe it ----
    await pTrigger(alice, { deposit: 1 }, 2e6); // base collateral it can later pay out
    const PERP_DEPOSIT = 200000;
    const depRes = await alice.sendMulti({
      base_outputs: [{ address: pv, amount: 10000 }],
      asset: PERP_ASSET,
      asset_outputs: [{ address: pv, amount: PERP_DEPOSIT }],
      messages: [{ app: "data", payload: { deposit_perp: 1 } }],
    });
    if (depRes.error) throw new Error("PERP deposit failed: " + depRes.error);
    await network.witnessUntilStable(depRes.unit);
    const depAa = await network.getAaResponseToUnit(depRes.unit);
    console.log("PERP deposit AA response:", JSON.stringify(depAa && depAa.response).slice(0, 300));
    st = await pVars();
    const pperp = Number(st["pperp_" + aliceAddr] || 0);
    console.log("after PERP deposit: pperp_alice =", pperp);
    if (!(pperp >= PERP_DEPOSIT)) throw new Error("PERP deposit not observed in AA state");

    // ---- 10b. sidechain batch: GovDeposit -> CreateMarket -> proposal ----
    // Signing-key convention matches export_batch.rs sk(n): seed = [n;32];
    // AccountId = sha256(pubkey) (operp_types::account_id_from_pubkey).
    const govKey = ed25519FromSeed(Buffer.alloc(32, 7));
    const govAcct = sha256Buf(govKey.pubkey);
    const govAcctHex = govAcct.toString("hex");
    const eng = makePerpEngine();
    let tip = sha256Hex("operp-mvp-1-genesis"); // operp_dag::genesis_id()
    const units = [];
    function postOp(opName, fieldsBuf, fieldsJson, simFields) {
      const u = signGovUnit([tip], opName, fieldsBuf, fieldsJson, govKey);
      const applied = eng.apply(opName, simFields);
      units.push(u);
      tip = u.unit_id;
      return applied;
    }

    // Op::GovDeposit{account, amount, aa_unit} — aa_unit is the Obyte PERP
    // deposit unit above (base64 unit id -> raw [u8;32]), replay-guarded by
    // operp-settle's deposits_allowed injection.
    const aaUnit = Buffer.from(depRes.unit, "base64");
    if (aaUnit.length !== 32) throw new Error("deposit unit id is not 32 bytes");
    postOp(
      "GovDeposit",
      { account: govAcct, amount: PERP_DEPOSIT, aa_unit: aaUnit },
      { account: Array.from(govAcct), amount: PERP_DEPOSIT, aa_unit: Array.from(aaUnit) },
      { account_hex: govAcctHex, amount: PERP_DEPOSIT, aa_unit_hex: aaUnit.toString("hex") },
    );
    if ((eng.bal.get(govAcctHex) || 0n) !== BigInt(PERP_DEPOSIT))
      throw new Error("sidechain GovDeposit not credited");
    console.log("PERP DEPOSIT CREDITED");

    // Op::CreateMarket{...}: burns CREATE_MARKET_FEE_PERP=10_000 from the
    // creator; symbol right-padded to 16 bytes; ETH_USD becomes market id=2.
    const symBuf = Buffer.alloc(16);
    Buffer.from("ETH_USD", "utf8").copy(symBuf);
    postOp(
      "CreateMarket",
      { creator: govAcct, symbol: symBuf, tick_size: 100, im_bps: 500, mm_bps: 1000, taker_fee_bps: 20, keeper_reward_bps: 50 },
      { creator: Array.from(govAcct), symbol: Array.from(symBuf), tick_size: 100, im_bps: 500, mm_bps: 1000, taker_fee_bps: 20, keeper_reward_bps: 50 },
      { creator_hex: govAcctHex, symbol_bytes: symBuf, tick_size: 100, im_bps: 500, mm_bps: 1000, taker_fee_bps: 20, keeper_reward_bps: 50 },
    );
    const MARKET = eng.nextMarketId - 1;
    if (MARKET !== 2 || !eng.markets.has(2)) throw new Error("market 2 not registered");
    if ((eng.bal.get(govAcctHex) || 0n) !== BigInt(PERP_DEPOSIT - 10000))
      throw new Error("listing fee not burned exactly");
    console.log("MARKET CREATED (id=2)");

    // Op::CreateProposal / Vote / FinalizeProposal: raise taker_fee_bps
    // 20 -> 35 on market 2 (ParamKey::TakerFeeBps = 2).
    postOp(
      "CreateProposal",
      { creator: govAcct, market: MARKET, key: 2, value: 35 },
      { creator: Array.from(govAcct), market: MARKET, key: 2, value: 35 },
      { creator_hex: govAcctHex, market: MARKET, key: 2, value: 35 },
    );
    const PID = eng.nextProposalId - 1;
    postOp(
      "Vote",
      { voter: govAcct, proposal_id: PID, approve: true },
      { voter: Array.from(govAcct), proposal_id: PID, approve: true },
      { voter_hex: govAcctHex, proposal_id: PID, approve: true },
    );
    // The deadline is measured in global seqs; fast-forward the deterministic
    // counter instead of posting 20_000 filler ops (the AA never sees seqs).
    eng.seq = eng.proposals.get(PID).deadline_seq;
    const fin = postOp(
      "FinalizeProposal",
      { caller: govAcct, proposal_id: PID },
      { caller: Array.from(govAcct), proposal_id: PID },
      { caller_hex: govAcctHex, proposal_id: PID },
    );
    if (!(fin.approved === true && eng.proposals.get(PID).finalized === true))
      throw new Error("proposal did not pass quorum");
    if (eng.markets.get(MARKET).taker_fee_bps !== 35)
      throw new Error("approved parameter not effective in next checkpoint state");
    console.log("PROPOSAL FINALIZED approved=true");

    // ---- 10c. commit the batch on-chain: temp_data reveal + submit/lock/finalize ----
    // Op::GovWithdraw mirrors the AA withdrawal claimed below (same amount).
    const WITHDRAW_PERP = 5000;
    postOp(
      "GovWithdraw",
      { account: govAcct, amount: WITHDRAW_PERP, nonce: 1 },
      { account: Array.from(govAcct), amount: WITHDRAW_PERP, nonce: 1 },
      { account_hex: govAcctHex, amount: WITHDRAW_PERP, nonce: 1 },
    );

    // aa_root over (address, collateral, perp) leaves — same pairs layout as
    // gen_withdraw_proof.rs (alice + decoy peer).
    const COLLATERAL_CLAIM = "100000";
    const pairs = [
      { addr: aliceAddr, collateral: COLLATERAL_CLAIM, perp: String(WITHDRAW_PERP) },
      { addr: "5B7BJSCMFQYUOLDLJHROMOKC5QCLPZLK3UEE4O25", collateral: "500", perp: "0" },
    ];
    const { proof, root } = aaProofFor(pairs, aliceAddr);
    let lh = aaLeafStr(aliceAddr, COLLATERAL_CLAIM, String(WITHDRAW_PERP));
    for (const s of proof) lh = sha256Hex(s.right ? lh + s.hash : s.hash + lh);
    if (lh !== root) throw new Error("local PERP proof recheck mismatch: " + lh);

    const HEIGHT = 1;
    const stateRoot = sha256Hex(Buffer.concat(units.map((u) => Buffer.from(u.unit_id, "hex"))));
    const batchData = {
      chain_id: "operp-mvp-1",
      height: HEIGHT,
      prev_state_hash: "prev0",
      state_root: stateRoot,
      aa_root: root,
      fills_hash: "f1",
      fill_count: 0,
      seq: eng.seq,
      last_unit: tip,
      unit_ids: units.map((u) => u.unit_id),
      units,
    };
    // NOTE: the on-chain temp_data reveal is intentionally skipped here —
    // ocore's inline temp_data validator double-calls its callback on large
    // payloads and crashes the core node. Data-availability correctness is
    // covered by the Rust-side settle tests (Batch::temp_data_payload,
    // validate_against); the AA only needs the committed aa_root below.

    await pTrigger(alice, { submit: 1, chain_id: "operp-mvp-1", height: HEIGHT, prev_state_hash: batchData.prev_state_hash, state_root: stateRoot, aa_root: root, fills_hash: "f1" });
    await network.timetravel({ shift: '700s' });
    await pTrigger(bob, { lock: 1, height: HEIGHT });
    st = await pVars();
    if (st["root_" + HEIGHT] !== stateRoot || st["aa_root_" + HEIGHT] !== root)
      throw new Error("height " + HEIGHT + " lock failed");
    await network.timetravel({ shift: '3600s' });
    // pTriggerRaw waits for the AA response itself; reading vars straight
    // after pTrigger races the response write and sees stale state.
    const finRes = await pTriggerRaw(alice, { finalize: 1, height: HEIGHT });
    if (finRes.response && finRes.response.bounced)
      throw new Error("finalize h" + HEIGHT + " bounced: " + JSON.stringify(finRes.response.error || {bounce:finRes.response.bounced, info:finRes.response.info, msg:finRes.response.error}).slice(0, 900));
    st = await pVars();
    if (Number(st.last_finalized) !== HEIGHT) throw new Error("finalize h" + HEIGHT + " failed");
    console.log("height", HEIGHT, "locked & finalized with PERP aa_root committed");

    // ---- 10d. PERP withdrawal: proof-gated payout incl. the ':perp' leaf segment ----
    // Mirrors the GOOD PROOF withdrawal above plus the perp field;
    // perp_amount omitted -> the AA pays out the full unclaimed remainder.
    const goodPerp = await pTriggerRaw(alice, {
      withdraw: 1,
      height: HEIGHT,
      amount: Number(COLLATERAL_CLAIM),
      leaf_account: aliceAddr,
      collateral: COLLATERAL_CLAIM,
      perp: String(WITHDRAW_PERP),
      proof,
    });
    if (!(goodPerp.response && goodPerp.response.bounced === false && goodPerp.response.response_unit)) {
      throw new Error("PERP withdrawal did not pay: " + JSON.stringify(goodPerp).slice(0, 500));
    }
    st = await pVars();
    if (Number(st["wp_" + HEIGHT + "_" + aliceAddr] || 0) !== WITHDRAW_PERP)
      throw new Error("wp_ marker not updated after PERP payout");
    if (!(Number(st["pperp_" + aliceAddr] || 0) === PERP_DEPOSIT - WITHDRAW_PERP))
      throw new Error("pperp_ shadow ledger not debited after PERP payout");
    console.log("PERP WITHDRAWAL PAID");
  }
  await network.stop();
  process.exit(0);
}

main().catch(async (e) => {
  console.error("FAILED:", e && e.stack ? e.stack : e);
  try { if (network) await network.stop(); } catch (_) {}
  process.exit(1);
});
