"use strict";

// Full vault-AA lifecycle test (security-hardened AA):
//   deposit -> submit -> candidate replacement -> early lock bounce ->
//   timetravel +600s -> lock -> early withdraw bounce ('not finalized') ->
//   challenge + respond success path (unfreeze, bond confiscated) ->
//   challenge failure path (no respond, window over -> height failed,
//   last_locked rollback, bond refunded) -> resubmit/lock/finalize ->
//   proof-gated withdraw (good proof pays; bad proof bounces).
//
// The withdrawal proof is generated by:
//   cargo run -p odex-settle --example gen_withdraw_proof
// which writes obyte-local/withdraw_claim.json.

const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const aaRoot = path.join(__dirname, "..", "vendor", "aa-testkit");
const nm = path.join(aaRoot, "node_modules");
process.env.NODE_PATH = [nm, process.env.NODE_PATH].filter(Boolean).join(path.delimiter);
process.env.devnet = "1";
require("module").Module._initPaths();

const { Testkit } = require(path.join(aaRoot, "main.js"));
const { Network } = Testkit({
  TESTDATA_DIR: path.join(__dirname, "testdata"),
  NETWORK_PORT: 16612,
});

function sha256Hex(s) {
  return crypto.createHash("sha256").update(s, "utf8").digest("hex");
}

async function trigger(wallet, data, amount) {
  const { unit, error } = await wallet.triggerAaWithData({
    toAddress: network.agent.vault,
    amount: amount === undefined ? 10000 : amount,
    data,
  });
  if (error) throw new Error(JSON.stringify(data).slice(0, 60) + ": " + error);
  await network.witnessUntilStable(unit);
  return unit;
}

async function vars() {
  const v = await network.wallet.alice.readAAStateVars(network.agent.vault);
  return v.vars || v;
}

async function expectBounce(promiseFn, needle) {
  const res = await promiseFn();
  const bounced =
    (res && res.bounced) ||
    (res && res.response && res.response.bounced) ||
    (res && res.objResponse && res.objResponse.bounced);
  const log = JSON.stringify(res || {});
  if (!bounced) throw new Error("expected bounce containing '" + needle + "', got: " + log.slice(0, 400));
  if (needle && !log.includes(needle))
    throw new Error("bounce reason mismatch: wanted '" + needle + "' in " + log.slice(0, 400));
  console.log("  bounced as expected:", needle);
}

// witnessUntilStable does not surface AA bounces; fetch the AA response instead.
async function triggerRaw(wallet, data, amount) {
  const { unit } = await wallet.triggerAaWithData({
    toAddress: network.agent.vault,
    amount: amount === undefined ? 10000 : amount,
    data,
  });
  await network.witnessUntilStable(unit);
  let resp = null;
  try {
    resp = await network.getAaResponseToUnit(unit);
  } catch (e) {
    resp = null;
  }
  return { unit, response: resp };
}

let network;

async function main() {
  network = await Network.create()
    .with.agent({ vault: path.join(__dirname, "agents/odex_vault.aa") })
    .with.wallet({ alice: 1e9 })
    .with.wallet({ bob: 1e9 })
    .run();

  const vault = network.agent.vault;
  const alice = network.wallet.alice;
  const bob = network.wallet.bob;
  console.log("vault", vault);

  // ---------- 1. deposit ----------
  await trigger(alice, { deposit: 1 }, 1e6);
  await trigger(bob, { deposit: 1 }, 2e6);
  let st = await vars();
  console.log("after deposits: bal_alice =", st["bal_" + (await alice.getAddress())]);
  if (!(st["bal_" + (await alice.getAddress())] > 0)) throw new Error("deposit not credited");

  // ---------- 2. submit height 1 + candidate replacement ----------
  const submit1 = { submit: 1, chain_id: "odex-mvp-1", height: 1, prev_state_hash: "prev0", state_root: "rootCAND1", aa_root: "aacand1", fills_hash: "f1" };
  await trigger(bob, submit1);
  // second submit must REPLACE the first (pre-lock)
  const submit2 = { submit: 1, chain_id: "odex-mvp-1", height: 1, prev_state_hash: "prev0", state_root: "rootFINAL1", aa_root: "aafinal1", fills_hash: "f1" };
  await trigger(alice, submit2);
  st = await vars();
  console.log("cand after replacement:", st["cand_root_1"], st["cand_aa_root_1"]);
  if (st["cand_root_1"] !== "rootFINAL1" || st["cand_aa_root_1"] !== "aafinal1")
    throw new Error("candidate replacement failed");

  // ---------- 3. early lock must bounce ----------
  const earlyLock = await triggerRaw(bob, { lock: 1, height: 1 });
  if (!JSON.stringify(earlyLock).includes("not stable yet"))
    throw new Error("early lock did not bounce with 'not stable yet': " + JSON.stringify(earlyLock).slice(0, 300));
  console.log("  early lock bounced as expected");

  // ---------- 4. stability window then lock ----------
  await network.timetravel({ shift: 700 });
  const lockRes = await triggerRaw(bob, { lock: 1, height: 1 });
  console.log("lock response:", JSON.stringify(lockRes.response && lockRes.response.responseVars), "bounced:", lockRes.response && lockRes.response.bounced, JSON.stringify(lockRes.response && lockRes.response.error || lockRes.response && lockRes.response.info));
  st = await vars();
  console.log("after lock: root_1 =", st["root_1"], "last_locked =", st["last_locked"]);
  if (st["root_1"] !== "rootFINAL1" || Number(st["last_locked"]) !== 1) throw new Error("lock failed");

  // ---------- 5. withdraw before finalize bounces ----------
  const earlyWd = await triggerRaw(alice, { withdraw: 1, amount: 1000 });
  if (!JSON.stringify(earlyWd).includes("not finalized"))
    throw new Error("early withdraw did not bounce: " + JSON.stringify(earlyWd).slice(0, 300));
  console.log("  pre-finalize withdraw bounced as expected");

  // ---------- 6. challenge + respond SUCCESS ----------
  const chalUnit = await bob.triggerAaWithData({ toAddress: vault, amount: 30000, data: { challenge: 1, height: 1 } });
  if (chalUnit.error) throw new Error("challenge: " + chalUnit.error);
  await network.witnessUntilStable(chalUnit.unit);
  st = await vars();
  if (Number(st["frozen_1"]) !== 1) throw new Error("challenge did not freeze");
  console.log("  frozen_1 =", st.frozen_1, "bond_bob =", st["bond_" + (await bob.getAddress())]);

  await network.timetravel({ shift: 100 });
  await trigger(alice, { respond: 1, height: 1, root_confirmed: "rootFINAL1" }, 20000);
  st = await vars();
  if (Number(st["frozen_1"]) !== 0) throw new Error("respond did not unfreeze");
  const bobBondAfterConfiscation = st["bond_" + (await bob.getAddress())];
  console.log("  unfrozen; bob bond after confiscation =", bobBondAfterConfiscation);
  if (!(bobBondAfterConfiscation >= 0)) throw new Error("bond accounting broken");

  // ---------- 7. finalize before window must bounce; then travel and finalize ----------
  const earlyFin = await triggerRaw(alice, { finalize: 1, height: 1 });
  if (!JSON.stringify(earlyFin).includes("window open"))
    throw new Error("early finalize did not bounce: " + JSON.stringify(earlyFin).slice(0, 200));
  console.log("  early finalize bounced as expected");

  // ---------- 8. challenge FAILURE path at height 2 ----------
  // submit+lock height 2 (bogus root), challenge it, never respond.
  await trigger(bob, { submit: 1, chain_id: "odex-mvp-1", height: 2, prev_state_hash: "rootFINAL1", state_root: "rootEVIL2", aa_root: "aaevil2", fills_hash: "f2" });
  await network.timetravel({ shift: 600 });
  await trigger(bob, { lock: 1, height: 2 });
  st = await vars();
  if (st.root_2 !== "rootEVIL2") throw new Error("height2 lock failed");
  await alice.triggerAaWithData({ toAddress: vault, amount: 30000, data: { challenge: 1, height: 2 } })
    .then(async (r) => { if (r.error) throw new Error(r.error); await network.witnessUntilStable(r.unit); });
  await network.timetravel({ shift: 3600 }); // operator stays silent past the window
  const failFin = await triggerRaw(alice, { finalize: 1, height: 2 }, 20000);
  st = await vars();
  console.log("after failed challenge: frozen_2 =", st.frozen_2, "last_locked =", st.last_locked);
  if (Number(st.frozen_2) !== 2) throw new Error("failure sweep did not mark frozen=2");
  if (Number(st.last_locked) !== 1) throw new Error("last_locked did not roll back");
  const aliceBondRefund = st["bond_" + (await alice.getAddress())];
  console.log("  alice bond after refund =", aliceBondRefund);
  if (!(aliceBondRefund > 0)) throw new Error("challenger bond not refunded");

  // ---------- 9. real proof withdraw against height 1 ----------
  // Height 1 was finalized? Not yet — we traveled far ahead; finalize h1 now.
  await trigger(alice, { finalize: 1, height: 1 });
  st = await vars();
  if (Number(st.last_finalized) !== 1) throw new Error("finalize h1 failed");
  console.log("height 1 finalized");

  // generate a REAL merkle proof from the Rust engine state
  require("child_process").execSync(
    "cargo run -p odex-settle --example gen_withdraw_proof",
    { cwd: path.join(__dirname, ".."), stdio: "inherit" }
  );
  const claim = JSON.parse(fs.readFileSync(path.join(__dirname, "withdraw_claim.json"), "utf8"));
  console.log("claim:", claim.leaf_account, claim.collateral);

  // sanity: recompute the root locally exactly like the AA does
  let h = sha256Hex("acct:" + claim.leaf_account + ":" + claim.collateral);
  for (const s of claim.proof) h = sha256Hex(s.right ? h + s.hash : s.hash + h);
  if (h !== claim.aa_root) throw new Error("local proof check mismatch: " + h);
  console.log("local proof recheck OK");

  // fund the AA enough to pay (it holds deposits from step 1)
  const wdAmount = Math.min(Number(claim.collateral), 900000);
  const good = await triggerRaw(alice, {
    withdraw: 1,
    height: 1,
    amount: wdAmount,
    leaf_account: claim.leaf_account,
    collateral: claim.collateral,
    proof: claim.proof,
  });
  if (JSON.stringify(good).includes("bounced")) {
    throw new Error("good proof withdrawn bounced: " + JSON.stringify(good).slice(0, 500));
  }
  console.log("GOOD PROOF WITHDRAWAL PAID");

  // bad proof must bounce
  const badProof = claim.proof.map((s, i) => (i === 0 ? { ...s, hash: s.hash.slice(0, -1) + (s.hash.endsWith("0") ? "1" : "0") } : s));
  const bad = await triggerRaw(alice, {
    withdraw: 1,
    height: 1,
    amount: wdAmount,
    leaf_account: claim.leaf_account,
    collateral: claim.collateral,
    proof: badProof,
  });
  if (!JSON.stringify(bad).includes("bad merkle root"))
    throw new Error("bad proof did not bounce with 'bad merkle root': " + JSON.stringify(bad).slice(0, 400));
  console.log("BAD PROOF BOUNCED AS EXPECTED");

  console.log("\nOK: full AA lifecycle passed");
  await network.stop();
  process.exit(0);
}

main().catch(async (e) => {
  console.error("FAILED:", e && e.stack ? e.stack : e);
  try { if (network) await network.stop(); } catch (_) {}
  process.exit(1);
});
