[package]
name = "odex-settle"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
odex-types = { workspace = true }
odex-dag = { workspace = true }
odex-state = { workspace = true }
odex-exec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
odex-book = { version = "0.1.0", path = "../odex-book" }

[dev-dependencies]
ed25519-dalek = { workspace = true }
